### ISSUE TITLE
Launch backup from remote dashboard

### ISSUE THREAD

**Issue by skollrc** [fabien-github/duplicati_dashboard#2]
Hi Fabien, 
(ou bonjour?)

Congrats for your great job first of all!

in your video we can see the possibility to launch jobs directly from the dashbord. I installed the dockers in a dedicate VM and I didn't see any option to do this. Is this option available only if the docker is installed in the same host?

![Capture d’écran du 2021-06-18 23-12-39](https://user-images.githubusercontent.com/35557003/122616754-54ff9680-d08b-11eb-9220-988a14e1c7bd.png)

Kind regards

**Comment by fabien-github** [comment]
Bonjour 👍 

Thanks for the feedback.

I'm sorry if the video is misleading but the right panel is not in the dashboard. It's a classical duplicati instance webui side by side just for the demo.

Have a nice day,
Fabien
