### ISSUE TITLE
Multiple duplicati servers

### ISSUE THREAD

**Issue by declanmarks** [fabien-github/duplicati_dashboard#3]
How could this be extended to use multiple Duplicati servers. I have multiple servers and don't what to set this up for each server.

**Comment by fabien-github** [comment]
Hello Declan,
If you have multiple Duplicati servers, the dashboard stack needs to be accessible over a network. Only do this on a trusted network.

For each servers, you setup the report endpoint :
**send-http-url:** http://localhost:8080/

So in your case, this endpoint will be the IP (or a DNS hostname) of the server who host the dashboad stack. (For example: http://192.168.1.5:8080)

That's all,
Have nice day
