### ISSUE TITLE
Sample JSON log

### ISSUE THREAD

**Issue by Timursan** [fabien-github/duplicati_dashboard#4]
Hi! You make big deal create duplicati_dashboard.
I test it sometime and ran into a problem.
I use "run-script-before-required" 
Script (checkISP.cmd) start duplcati task only if I use main ISP1 not backup ISP2 (it very expensive use traffic through backup ISP2).
Everything work but I don’t see on dashboard when main ISP fail and backup didn’t make because duplicati task didn’t start and don’t send log to telegraf.
So, I want send static JSON log by curl library in case error with main ISP1 connection and use description like - "Fail main ISP1".
Can you help me find sample JSON log what parsed telegraf with warning state?

**Comment by fabien-github** [comment]
Hello,

Thank for your message, i didn't know the `--run-script-before-required` option. It's a really good one in your case.

You can find the telegraf configuration here, with all usefull extracted keys for the dashboard :
[https://github.com/fabien-github/duplicati_dashboard/blob/main/telegraf/telegraf.conf#L207](https://github.com/fabien-github/duplicati_dashboard/blob/main/telegraf/telegraf.conf#L207)

The `Data` object is exactly the same as the complete log you can find in the result of the job in the duplicati interface.
You have an other top level object in the JSON named : `Extra`, with two key `OperationName` and `backup-name`.

```
{
  "Extra": {
    "OperationName": "Backup",
    "backup-name": "My-Important-Folder"
  },
  "Data": {
    "DeletedFiles": 0,
    "DeletedFolders": 0,
    "ModifiedFiles": 0,
    ...
  }
}
```

Hope it will help,
Have a nice day.
