### ISSUE TITLE
No Reports

### ISSUE THREAD

**Issue by seanmccabe** [fabien-github/duplicati_dashboard#5]
Seems no reports are being processed at the monitoring site.
I’ve configured the backup like a hundred before and as per the video set the reporting url as can see below:

![image](https://user-images.githubusercontent.com/12243212/205164243-85d8ab0d-a274-46c4-9186-7ff7a52650d2.png)

Report URL: https://www.duplicati-monitoring.com/log/dttech/BOk2mmM4Kuk3PuS/34199

However, I’m not getting any reports received on the other end and have full outbound internet access. 

Any suggestions to resolve this would be great.

**Comment by fabien-github** [comment]
Hello,

Duplicati Dashboard is not the same project than https://www.duplicati-monitoring.com

On their website, you can contact them at this address : mail@duplicati-monitoring.com
