### ISSUE TITLE
Backup over more than 30 days rotation

### ISSUE THREAD

**Issue by Timursan** [fabien-github/duplicati_dashboard#7]
Hello!
I use your dashboard and have backup over more than 30 days rotation.
Found in readme how to change but don`t understand how to do it.
Should I connect to some container and make a change to some config?
Can you describe much wider how to change parametr ?

 from(bucket: v.defaultBucket)
|> range(start: -30d)** 

If it possible step by step.
Big thanks!

**Comment by fabien-github** [comment]
Hello !

Like you saw in the README, you will need to update the dashboard configuration for the `Backup` variable. The backup name discovery range need to be at least 2 time longer than the longest duration between two iteration of a backup.

**In Dashboard Settings -> Variables -> Backup -> Query**

You will see this line :
```|> range(start: -90d)```

Then edit the start parameter as you wish.

---
Theses 3 panels need at least two backups reporting to work :
- Last reported status
- Last reported variations
- Alerting graph

**On the first panel at the title bar -> Click the arrow down on the right corner -> Edit -> On the query tab -> Update the start parameter on the range line**

Repeat for each 3 panels.

Example :
```|> range(start: -30d)``` -> ```|> range(start: -60d)```

Be aware, theses changes can have an impact over dashboard reactivity and performance.
