### ISSUE TITLE
No data Result

### ISSUE THREAD

**Issue by w3bservice** [fabien-github/duplicati_dashboard#8]
Hello, first of all a great work, the dashboard. My question is about the status when no more backups are in the dashboard so after a defined time no backups are shown in the dashboard. So the status "No data" how to include the status in the alert. Background is if the backup is no longer working or the user is on vacation. So that also in this case an alert goes. I have taken out the whole Docker substructure and built after your Configs from the Docker a locale configuration, because it is first a LXC container and just more dashboards run on it. I also extended the alerting with Slack. The alert "No data" should be like "Failure".

**Comment by fabien-github** [comment]
Hello,
i'm not sure if i correctly understand all of your message, tell me if i'm missing something. I think you said that you want to be alerted when you get "No data" status.

The dashboard doesn't have the capacity to track backups, It's just the result of reports sent by duplicati instances. You are stepping in a common pattern when you make assomption about missing report. But you are the only one how known a report is missing. The dashboard only show you reports during a preset range (https://github.com/fabien-github/duplicati_dashboard/tree/main#backup-over-more-than-30-days-rotation). In your case, it can be justified but in many case you don't want to sent an alert so i will not change that.

For _Background is if the backup is no longer working_, you just need to purge the backup from the database :
https://github.com/fabien-github/duplicati_dashboard#deleting-removed-backup-data

For _the user is on vacation_, you can extend the range discovery to capture a more large set of data to manage period where backup is voluntary stopped : https://github.com/fabien-github/duplicati_dashboard/issues/7#issuecomment-1522147803

In v2, alerting are provisioned with a dedicated file and his own query with a detection range over the last 30 days : https://github.com/fabien-github/duplicati_dashboard/blob/3e1d558d54c6b3ecbb7ed67627a812c5dd060f31/grafana/provisioning/alerting/duplicati_alert.yml#L30

**Comment by w3bservice** [comment]
Hello,
do not overlook But we are looking for an alert when the backup has no data, whether the user is on vacation, or the user has stopped the backup, or Duplicati has an error that is not shown in the dashboard. It was just a question of how to implement something like this. We have GLPI to manage our computers and when a computer is taken down, a webhook deletes the data in InfluxDB. Works great, via shellscript and via curl. We are just looking for a way to alert in case there is no data "No data" after 30 days. then a message should come.

Hallo,

nicht übersehen. Sondern wir sind auf der Suche einer Alamierung wenn Das Backup keine Daten hat, sei es der User hat Urlaub, oder der User hat das Backup gestoppt oder Duplicati hat einen Fehler die nicht im Dashboard aufgezeigt wird. Es war nur die Frage wie man sowas implementieren kann. Wir haben zur Verwaltung unserer Rechner GLPI. und wenn ein Rechner abgebaut wird, wird über einen Webhook die Daten in der InfluxDB gelöscht. Funktioniert super, per Shellscript und per curl. Wir suchen nur nach einer Möglichkeit zur Alamierung für den Fall das nach 30 Tagen keine Daten "No data" vorhanden sind. dann sollte eine Meldung kommen.

thx


p.s. gerne auch in deutsch

**Comment by fabien-github** [comment]
Hello,
I think you need an other way to monitor because you can't depend only on the reports sent by clients. You need to periodicly connect to duplicati instances for checking their states. Like a real monitoring system.

Duplicati doesn't seem to have an API. This project (https://github.com/Pectojin/duplicati-client) could be a good start to create a script that retrieve data and send it to influxdb.

Fabien
