### ISSUE TITLE
Log Window Showing Error After Recieving Data

### ISSUE THREAD

**Issue by scssnys** [fabien-github/duplicati_dashboard#9]
Thank you so much for this dashboard - it's amazing. Having a small issue with the logs being displayed.

Ran a test backup & it worked fine & showed the logs. 
Ran a few other backups and the logs failed to show with this error, any idea?

![image](https://github.com/fabien-github/duplicati_dashboard/assets/54947671/076ad4e0-257f-41cc-8cea-e3681e7f7d18)

On the 'failed' backup jobs, it shows this error:
![image](https://github.com/fabien-github/duplicati_dashboard/assets/54947671/6ebb3039-51fd-46d0-a33c-d9b5234b5454)
![image](https://github.com/fabien-github/duplicati_dashboard/assets/54947671/33edd2e6-5b38-4641-bb25-6cb5270e5d42)

**Comment by fabien-github** [comment]
Hello,

I'm glad you like the dashboard.

i can't reproduce our issue on my end. From the error you're getting, it looks like there's an issue with the data on your influxdb instance. It's even strange that you can retrieve your first backup report.

Check if grafana can access your influxdb database :
Configuration -> Data sources -> InfluxDB -> Test

Are your backup scheduled over a long period of time ?

https://github.com/fabien-github/duplicati_dashboard?tab=readme-ov-file#backup-over-more-than-30-days-rotation

**Comment by scssnys** [comment]
thank you. The Influx DB test was successful:

![image](https://github.com/fabien-github/duplicati_dashboard/assets/54947671/ba653778-7715-42a7-9197-a763d19a697c)

Yes we're logging backups past 30 days, we're about 60 days in for 10 computers. Should i make the edit you linked to?

**Comment by fabien-github** [comment]
Yes, you should try it. Copy the dashboard in grafana to edit it or update the value directly on all queries in the json dashboard file.

https://github.com/fabien-github/duplicati_dashboard?tab=readme-ov-file#grafana-configuration-locked
